version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: samlion
      POSTGRES_PASSWORD: Sam369333693
      POSTGRES_DB: social_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  adminer_ui:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

  web:
    build: .
    container_name: flask_app
    restart: always
    environment:
      - DATABASE_URL=postgresql://samlion:Sam369333693@db:5432/social_network
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend

  nginx_proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
